Do not build statically by default
decred/decred-seeder pull request #15
Opened 2018-03-05 23:48 UTC by jcvernaleo

Closes #13

2018-03-05 23:50 UTC, jcvernaleo commented
@jrick I saw the same issue when I try to build on CentOS.  Since I'm not an expert on redhat style packages (`-static` seems fine on Debian based systems) I figured it was best to default to normal, non-static linking since that is probably right in most cases while making it easy enough for me to build statically without keeping local patches.

2018-03-06 15:48 UTC, jrick approved these changes

2018-03-06 15:50 UTC, jrick requested changes

2018-03-06 15:50 UTC, jrick commented on README.md
> +To build statically (useful for running on minimal debian servers that may not have all of the required libs installed:
actually looks like you're missing the closing parentheses here

2018-03-06 16:01 UTC, jcvernaleo commented
Fix the readme and squashed.

2018-03-06 17:06 UTC, jrick approved these changes

2018-03-06 17:08 UTC, merged